// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car_rent_api2.Server.Database;

#nullable disable

namespace car_rent.Server.Migrations
{
    [DbContext(typeof(SearchEngineDbContext))]
    [Migration("20241119183510_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("car_rent_api2.Server.Database.Company", b =>
                {
                    b.Property<int>("Company_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_ID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.Offer", b =>
                {
                    b.Property<int>("Offer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Offer_ID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Offer_ID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.Rent", b =>
                {
                    b.Property<int>("Rent_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rent_ID"));

                    b.Property<int>("Company_ID")
                        .HasColumnType("int");

                    b.Property<int>("Offer_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rent_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Return_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Rent_ID");

                    b.HasIndex("Company_ID")
                        .IsUnique();

                    b.HasIndex("Offer_ID")
                        .IsUnique();

                    b.HasIndex("User_ID");

                    b.ToTable("History");
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Issue_date_driver_license")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.Rent", b =>
                {
                    b.HasOne("car_rent_api2.Server.Database.Company", "Company")
                        .WithOne("Rent")
                        .HasForeignKey("car_rent_api2.Server.Database.Rent", "Company_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("car_rent_api2.Server.Database.Offer", "Offer")
                        .WithOne("Rent")
                        .HasForeignKey("car_rent_api2.Server.Database.Rent", "Offer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("car_rent_api2.Server.Database.User", "User")
                        .WithMany("Rents")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.Company", b =>
                {
                    b.Navigation("Rent")
                        .IsRequired();
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.Offer", b =>
                {
                    b.Navigation("Rent")
                        .IsRequired();
                });

            modelBuilder.Entity("car_rent_api2.Server.Database.User", b =>
                {
                    b.Navigation("Rents");
                });
#pragma warning restore 612, 618
        }
    }
}
