@car_rent.Server_HostAddress = http://localhost:5109

GET {{car_rent.Server_HostAddress}}/cars/
Accept: application/json

POST {{car_rent.Server_HostAddress}}/rent/
Accept: application/json

GET {{car_rent.Server_HostAddress}}/history/
Accept: application/json
###
