name: Build and deploy ASP.Net Core app with React to Azure Web App - carrentsearchengine

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DB_CONNECTION_STRING_WYSZUKIWARKA: ${{ secrets.DB_CONNECTION_STRING_WYSZUKIWARKA }}
      DOTNET_CARRENT_API1: ${{secrets.DOTNET_CARRENT_API1}}
      DOTNET_CARRENT_API2: ${{secrets.DOTNET_CARRENT_API2}}

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update -c SearchEngineDbContext --project car_rent.Server
        env:
          ASPNETCORE_ENVIRONMENT: Development

      # Build the .NET Core backend
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the .NET Core backend (for deployment)
      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      # Upload artifacts for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: ${{env.DOTNET_ROOT}}/myapp


  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the artifacts from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88030035BD8C42ECB36455869456EE1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_25E3981155F24CD9816B849645464E71 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14770D7C77B14136AA2BEB84C172BCF9 }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carrentsearchengine'
          slot-name: 'Production'
          package: .



